import { useState, useMemo } from 'react';
import { Star, ChevronRight, ChevronLeft, RotateCcw, Copy, CheckCircle } from 'lucide-react';
import { Card } from '../components/ui/Card';
import { Button } from '../components/ui/Button';
import { CircularProgress } from '../components/ui/CircularProgress';
import {
  useAppContext,
  useContentItems,
  useCampaigns,
  useGraderResponses,
  nowISO,
} from '../context/AppContext';
import { calculateScore } from '../utils/scoring';

const QUESTIONS = [
  'Do you have a defined target audience with specific demographics and pain points?',
  'Do you track which content pieces perform best and use that data to guide future content?',
  'Do you repurpose content across multiple platforms (e.g., blog → social → email)?',
  'Do you maintain a consistent brand voice across all channels?',
  'Do you follow up on leads or inquiries generated by your content?',
  'Do you plan and schedule content at least 2 weeks in advance?',
  'Is your content strategy directly tied to a specific revenue or business goal?',
  'Do you A/B test different headlines, hooks, or formats to optimize performance?',
  'Do you review your analytics data at least once per month?',
  'Do you have a documented content strategy (written down, not just in your head)?',
];

const SCORE_LABELS: Record<number, string> = {
  1: 'Never',
  2: 'Rarely',
  3: 'Sometimes',
  4: 'Usually',
  5: 'Always',
};

const GRADE_CONFIG: Record<string, { label: string; color: string; description: string }> = {
  A: {
    label: 'Strong',
    color: '#22C55E',
    description: "You have a solid marketing foundation. Focus on consistency and optimization.",
  },
  B: {
    label: 'Good',
    color: '#84CC16',
    description: "Your strategy is working. A few targeted improvements will move the needle significantly.",
  },
  C: {
    label: 'Fair',
    color: '#F59E0B',
    description: "There's clear room for improvement. Address the lowest-scoring areas first.",
  },
  D: {
    label: 'Weak',
    color: '#F97316',
    description: "Your marketing needs structural work. Start with consistency and goal clarity.",
  },
  F: {
    label: 'Poor',
    color: '#EF4444',
    description: "Your marketing is not yet working for you. Start with the basics: one platform, one goal, consistent posting.",
  },
};

const SCORE_BAR_LABELS = [
  { key: 'consistency', label: 'Posting Consistency', max: 25 },
  { key: 'platformDiversity', label: 'Platform Diversity', max: 25 },
  { key: 'goalCoverage', label: 'Goal Coverage', max: 25 },
  { key: 'pipelineHealth', label: 'Pipeline Health', max: 25 },
];

export default function MarketingGrader() {
  const { dispatch } = useAppContext();
  const contentItems = useContentItems();
  const campaigns = useCampaigns();
  const savedResponses = useGraderResponses();

  const [phase, setPhase] = useState<'intro' | 'quiz' | 'results'>('intro');
  const [currentQ, setCurrentQ] = useState(0);
  const [responses, setResponses] = useState<Record<number, number>>(savedResponses.responses ?? {});
  const [copied, setCopied] = useState(false);

  const score = useMemo(
    () => calculateScore(contentItems, campaigns, { responses, completedAt: nowISO() }),
    [contentItems, campaigns, responses]
  );

  const gradeConfig = GRADE_CONFIG[score.grade] ?? GRADE_CONFIG['C'];

  function handleAnswer(val: number) {
    setResponses((r) => ({ ...r, [currentQ]: val }));
  }

  function goNext() {
    if (currentQ < QUESTIONS.length - 1) {
      setCurrentQ((q) => q + 1);
    } else {
      // Save and show results
      dispatch({
        type: 'SAVE_GRADER',
        payload: { responses, completedAt: nowISO() },
      });
      setPhase('results');
    }
  }

  function goPrev() {
    if (currentQ > 0) setCurrentQ((q) => q - 1);
  }

  function reset() {
    setResponses({});
    setCurrentQ(0);
    setPhase('intro');
  }

  function buildReport(): string {
    const lines = [
      'BVP MARKETING GRADER REPORT',
      '============================',
      `Overall Score: ${score.total}/100 — Grade ${score.grade} (${gradeConfig.label})`,
      '',
      'SCORE BREAKDOWN',
      ...SCORE_BAR_LABELS.map(
        ({ key, label, max }) =>
          `  ${label}: ${score[key as keyof typeof score]}/${max}`
      ),
      `  Self-Assessment: ${score.selfAssessment}/100`,
      '',
      'RECOMMENDATIONS',
      ...score.recommendations.map((r, i) => `  ${i + 1}. ${r}`),
      '',
      `Generated: ${new Date().toLocaleDateString()}`,
      'Powered by BVP Marketing Agent — botvaultpro@outlook.com',
    ];
    return lines.join('\n');
  }

  async function copyReport() {
    try {
      await navigator.clipboard.writeText(buildReport());
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback — select text
    }
  }

  return (
    <div className="p-5 md:p-6 max-w-2xl mx-auto space-y-5">
      {/* Header */}
      <div>
        <h1 className="text-xl font-heading font-bold text-[#F5F5F5] tracking-wide uppercase">
          Marketing Grader
        </h1>
        <p className="text-xs text-[#6B6B6B] mt-0.5">
          Score your marketing strategy and get personalized recommendations
        </p>
      </div>

      {/* Intro */}
      {phase === 'intro' && (
        <Card>
          <div className="flex flex-col items-center text-center py-6 gap-4">
            <div className="p-4 rounded-2xl bg-orange-500/10 border border-orange-500/20">
              <Star size={28} className="text-orange-400" />
            </div>
            <div>
              <h2 className="text-lg font-heading font-bold text-[#F5F5F5]">
                Grade Your Marketing
              </h2>
              <p className="text-sm text-[#6B6B6B] mt-1 max-w-md">
                Answer 10 quick questions and we'll combine your responses with your logged data to give
                you a real, actionable marketing score.
              </p>
            </div>

            {/* Auto-score preview */}
            <div className="w-full bg-[#0A0A0A] rounded-xl border border-[#2A2A2A] p-4 text-left">
              <p className="text-[10px] font-medium text-[#6B6B6B] uppercase tracking-wider mb-3">
                Auto-scored from your data
              </p>
              <div className="space-y-2">
                {SCORE_BAR_LABELS.map(({ key, label, max }) => {
                  const val = score[key as keyof typeof score] as number;
                  return (
                    <div key={key}>
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs text-[#A3A3A3]">{label}</span>
                        <span className="text-xs text-[#6B6B6B]">
                          {val}/{max}
                        </span>
                      </div>
                      <div className="h-1.5 rounded-full bg-[#2A2A2A] overflow-hidden">
                        <div
                          className="h-full rounded-full bg-orange-500 transition-all duration-500"
                          style={{ width: `${(val / max) * 100}%` }}
                        />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            <Button onClick={() => { setCurrentQ(0); setPhase('quiz'); }}>
              Start Questionnaire <ChevronRight size={14} />
            </Button>

            {Object.keys(savedResponses.responses).length > 0 && (
              <button
                onClick={() => setPhase('results')}
                className="text-xs text-orange-400 hover:text-orange-300 underline"
              >
                View last results
              </button>
            )}
          </div>
        </Card>
      )}

      {/* Quiz */}
      {phase === 'quiz' && (
        <div className="space-y-4">
          {/* Progress */}
          <div>
            <div className="flex items-center justify-between mb-2">
              <span className="text-xs text-[#6B6B6B]">
                Question {currentQ + 1} of {QUESTIONS.length}
              </span>
              <span className="text-xs text-[#6B6B6B]">
                {Math.round(((currentQ + 1) / QUESTIONS.length) * 100)}%
              </span>
            </div>
            <div className="h-1 rounded-full bg-[#2A2A2A] overflow-hidden">
              <div
                className="h-full rounded-full bg-orange-500 transition-all duration-300"
                style={{ width: `${((currentQ + 1) / QUESTIONS.length) * 100}%` }}
              />
            </div>
          </div>

          {/* Question card */}
          <Card>
            <p className="text-sm font-medium text-[#F5F5F5] leading-relaxed mb-6">
              {QUESTIONS[currentQ]}
            </p>

            {/* Scale buttons */}
            <div className="grid grid-cols-5 gap-2 mb-6">
              {[1, 2, 3, 4, 5].map((val) => (
                <button
                  key={val}
                  onClick={() => handleAnswer(val)}
                  className={`flex flex-col items-center gap-1 p-3 rounded-xl border text-center transition-all ${
                    responses[currentQ] === val
                      ? 'bg-orange-500/10 border-orange-500/40 text-orange-400'
                      : 'bg-[#0A0A0A] border-[#2A2A2A] text-[#6B6B6B] hover:border-[#3A3A3A] hover:text-[#A3A3A3]'
                  }`}
                >
                  <span className="text-xl font-heading font-bold">{val}</span>
                  <span className="text-[9px] leading-tight">{SCORE_LABELS[val]}</span>
                </button>
              ))}
            </div>

            {/* Nav */}
            <div className="flex items-center justify-between">
              <Button
                variant="ghost"
                size="sm"
                onClick={goPrev}
                disabled={currentQ === 0}
              >
                <ChevronLeft size={14} /> Back
              </Button>
              <Button
                size="sm"
                onClick={goNext}
                disabled={responses[currentQ] === undefined}
              >
                {currentQ === QUESTIONS.length - 1 ? 'See Results' : 'Next'}
                <ChevronRight size={14} />
              </Button>
            </div>
          </Card>
        </div>
      )}

      {/* Results */}
      {phase === 'results' && (
        <div className="space-y-4">
          {/* Score card */}
          <Card>
            <div className="flex flex-col sm:flex-row items-center gap-6 py-2">
              <CircularProgress
                value={score.total}
                size={130}
                strokeWidth={10}
                color={gradeConfig.color}
              />
              <div className="flex-1 text-center sm:text-left">
                <div className="flex items-center gap-2 justify-center sm:justify-start mb-1">
                  <span
                    className="text-4xl font-heading font-bold"
                    style={{ color: gradeConfig.color }}
                  >
                    {score.grade}
                  </span>
                  <span className="text-xl font-heading text-[#F5F5F5]">{gradeConfig.label}</span>
                </div>
                <p className="text-sm text-[#A3A3A3] leading-relaxed max-w-sm">
                  {gradeConfig.description}
                </p>
              </div>
            </div>
          </Card>

          {/* Score breakdown */}
          <Card>
            <h2 className="text-xs font-heading font-semibold text-[#F5F5F5] uppercase tracking-wide mb-4">
              Score Breakdown
            </h2>
            <div className="space-y-3">
              {SCORE_BAR_LABELS.map(({ key, label, max }) => {
                const val = score[key as keyof typeof score] as number;
                const pct = (val / max) * 100;
                return (
                  <div key={key}>
                    <div className="flex items-center justify-between mb-1.5">
                      <span className="text-xs text-[#A3A3A3]">{label}</span>
                      <span className="text-xs font-medium text-[#F5F5F5]">
                        {val}/{max}
                      </span>
                    </div>
                    <div className="h-2 rounded-full bg-[#2A2A2A] overflow-hidden">
                      <div
                        className="h-full rounded-full transition-all duration-700"
                        style={{
                          width: `${pct}%`,
                          backgroundColor: pct >= 70 ? '#22C55E' : pct >= 40 ? '#F97316' : '#EF4444',
                        }}
                      />
                    </div>
                  </div>
                );
              })}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <span className="text-xs text-[#A3A3A3]">Self-Assessment</span>
                  <span className="text-xs font-medium text-[#F5F5F5]">{score.selfAssessment}/100</span>
                </div>
                <div className="h-2 rounded-full bg-[#2A2A2A] overflow-hidden">
                  <div
                    className="h-full rounded-full bg-blue-500 transition-all duration-700"
                    style={{ width: `${score.selfAssessment}%` }}
                  />
                </div>
              </div>
            </div>
          </Card>

          {/* Recommendations */}
          {score.recommendations.length > 0 && (
            <Card>
              <h2 className="text-xs font-heading font-semibold text-[#F5F5F5] uppercase tracking-wide mb-3">
                Personalized Recommendations
              </h2>
              <div className="space-y-3">
                {score.recommendations.map((rec, i) => (
                  <div key={i} className="flex gap-3 p-3 rounded-xl bg-[#0A0A0A] border border-[#1A1A1A]">
                    <div className="flex-shrink-0 w-5 h-5 rounded-full bg-orange-500/10 border border-orange-500/20 flex items-center justify-center">
                      <span className="text-[9px] font-bold text-orange-400">{i + 1}</span>
                    </div>
                    <p className="text-xs text-[#A3A3A3] leading-relaxed">{rec}</p>
                  </div>
                ))}
              </div>
            </Card>
          )}

          {/* Actions */}
          <div className="flex flex-wrap gap-3">
            <Button variant="secondary" onClick={reset}>
              <RotateCcw size={14} /> Retake
            </Button>
            <Button onClick={copyReport}>
              {copied ? <CheckCircle size={14} /> : <Copy size={14} />}
              {copied ? 'Copied!' : 'Export Report'}
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}
