import { Metadata } from "next";
import SiteBuilderDemoClient from "./SiteBuilderDemoClient";

export const metadata: Metadata = {
  title: "Free AI Website Generator — SiteBuilder Pro by Bot Vault Pro",
  description: "Enter your business name and type. Get a complete, professional website generated by AI in 60 seconds. Free demo — no account required.",
  openGraph: {
    title: "Free AI Website Generator — SiteBuilder Pro",
    description: "AI builds your business website in 60 seconds. Free demo, no account needed.",
    type: "website",
  },
};

export default function SiteBuilderDemoPage() {
  return <SiteBuilderDemoClient />;
}
